.PHONY: clean

EXECUTABLE_DIRECTORY = bin
OBJECT_DIRECTORY = obj
SOURCE_DIRECTORY = src
RESOURCES_DIRECTORY = res

INCLUDES = -I"include"
LIBRARIES = -lglfw -lGL -lm
WARNINGS = -Wall -Wextra -Wpedantic
DEBUG = -DDEBUG -g
OPTIMIZE = -Og
CXX_STANDARD = -std=c++17

EXECUTABLE = ${EXECUTABLE_DIRECTORY}/fly
MAIN_CXX = ${SOURCE_DIRECTORY}/main.cxx
MAIN_OBJ = ${OBJECT_DIRECTORY}/main.o
OBJECTS = ${OBJECT_DIRECTORY}/main.o

${EXECUTABLE}: ${EXECUTABLE_DIRECTORY} ${OBJECT_DIRECTORY} ${OBJECTS}
	${CXX} -o $@ ${OBJECTS} ${LIBRARIES}

${EXECUTABLE_DIRECTORY}:
	mkdir -p "$@"
	cp -rv "${RESOURCES_DIRECTORY}" "$@"

${OBJECT_DIRECTORY}:
	mkdir -p "$@"

${MAIN_OBJ}: ${MAIN_CXX}
	${CXX} -c -o $@ $< ${INCLUDES} ${CXX_STANDARD} ${WARNINGS} ${DEBUG} ${OPTIMIZE}

clean:
	rm -rf ${EXECUTABLE_DIRECTORY} ${OBJECT_DIRECTORY}
